# -*- coding: utf-8 -*-
"""📚 Python Uygulama 2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fCm7DMWRws_PtJ46SSN9tWn6-t4JkNEd
"""

def euclideanDistance(point1, point2):
    x1, y1 = point1
    x2, y2 = point2
    return math.sqrt((x2 - x1) ** 2 + (y2 - y1) ** 2)

points = []
n = int(input("kaç adet nokta gireceğinizi yazın?: "))

for i in range(n):
    x = float(input(f"{i+1}. noktanın x koordinatını girin: "))
    y = float(input(f"{i+1}. noktanın y koordinatını girin: "))
    points.append((x, y))

print("Girilen noktalar:", points)

distances = []

for i in range(len(points)):
    for j in range(i + 1, len(points)):
        distance = euclideanDistance(points[i], points[j])
        distances.append(distance)

print("Hesaplanan mesafeler:", distances)

if distances:
    min_distance = min(distances)
    print("Minimum mesafe:", min_distance)
else:
    print("nokta girdisi.")

